### ISSUE TITLE
Store dependencies as a tree of SPDX files (instead of a flat list)

### ISSUE THREAD

**Issue by silverhook** [oss-review-toolkit/ort#4099]
Currently ORT’s SPDX output produces a flat list of all the dependencies and their (package-level) licenses.

This is a huge missed opportunity, as SPDX spec does actually include fields such as [`Relationship`](https://spdx.github.io/spdx-spec/7-relationships-between-SPDX-elements/#71-relationship) and [`ExternalDocumentRef`](https://spdx.github.io/spdx-spec/2-document-creation-information/#26-external-document-references), which could be used to:
- create a separate SPDX file for each package, which includes file-level info (ScanCode already does this, when used by ORT to scan the deps)
- create a SPDX file for the main package being analyzed, and in it
- link to SPDX files of other relevant packages using the appropriate relationships – e.g. for a dependency `DEPENDS_ON`

This would make the output not only easier to parse, since the hierarchy would not be lost; but would also make the results re-usable, as the SPDX file for a certain package could simply be reused if that package is a dependency in another scan later on.

See also https://github.com/oss-review-toolkit/ort/issues/1913#issuecomment-638809109 where relationships were mentioned as a todo.

cc: @maxhbr

**Comment by sschuberth** [comment]
To clarify: IIUC the SPDX reporter already *does* maintain package hierarchy, see e.g. this expected test result file:

https://github.com/oss-review-toolkit/ort/blob/d9e78272c85273b8508b67f652bb511994ff5cba/reporter/src/funTest/assets/spdx-document-reporter-expected-output.spdx.yml#L155-L158

It's just that all packages are captured as part of a single SPDX file. So this request is not so much about "not loosing hierarchy", but simply to "externalize" the related packages to separate files.

**Comment by maxhbr** [comment]
I generated the `document.spdx.yml` yesterday for `mime-types` and in the result each packages is always a dependeny_of the root package (and not of another package):

```
$  cat document.spdx.yml | grep DEPENDENCY_OF -B2
- spdxElementId: "SPDXRef-Package-1-acorn"
  relatedSpdxElement: "SPDXRef-Package-0-root-package"
  relationshipType: "DEPENDENCY_OF"
--
- spdxElementId: "SPDXRef-Package-10-ajv"
  relatedSpdxElement: "SPDXRef-Package-0-root-package"
  relationshipType: "DEPENDENCY_OF"
--
- spdxElementId: "SPDXRef-Package-100-character-entities-legacy"
  relatedSpdxElement: "SPDXRef-Package-0-root-package"
  relationshipType: "DEPENDENCY_OF"
--
[...]
--
- spdxElementId: "SPDXRef-Package-994-helper-module-transforms"
  relatedSpdxElement: "SPDXRef-Package-0-root-package"
  relationshipType: "DEPENDENCY_OF"
--
- spdxElementId: "SPDXRef-Package-997-helper-optimise-call-expression"
  relatedSpdxElement: "SPDXRef-Package-0-root-package"
  relationshipType: "DEPENDENCY_OF"
```

This is effectively a flat list.

**Comment by sschuberth** [comment]
> each packages is always a dependeny_of the root package (and not of another package)

Then that's a bug, I'd say. @fviernau do you agree?

**Comment by fviernau** [comment]
@sschuberth  IIRC it was intentionally implemented as flat list, leaving the tree information up for a future iteration. So, I don't think it's a bug.

**Comment by sschuberth** [comment]
But a limitation that we want to lift; i.e. we do not want / need to maintain the current (wrong) behavior, correct?

**Comment by tsteenbe** [comment]
Yes, we kind of paused SPDX reporter development due to other priorities and unclarities/quirks in SPDX 2.2.

To my recollection the things of open SPDX reporter to-do items:
- Add dependency tree information as captured by ORT in SPDX, if user has specified excludes use exclude reason instead of DEPENDENCY_OF
- Create a full / maximum detail report that includes as much of the data ORT captures to the extend SPDX supports it. Think of file findings included as SPDX files, applied ORT curations as SPDX annotations.  However, for file level details their need to be an option to not include certain packages - several ORT users have indicated that they want to produce SPDX but do not want to share file finding for their proprietary software.

I had similar idea as @silverhook of splitting up the single SPDX into multiple e.g. have a catalog of SPDX files for each package and then the exchange with third parties refers to this catalog to keeping the exchange SPDX file relative small.

**Comment by sschuberth** [comment]
> Question to figure out then is that ORT would then need to support a mechanism to allow user to set URI or SPDX document location so that linking between the files will work.

That's actually [already implemented](https://github.com/oss-review-toolkit/ort/pull/3863).

**Comment by silverhook** [comment]
So, what is missing then?

**Comment by sschuberth** [comment]
> So, what is missing then?

Some one who's willing and able to contribute a PR 😉

**Comment by silverhook** [comment]
> Some one who's willing and able to contribute a PR :wink: 

Ah, _that_ standard minor detail ;)

Would love to help, but I’d trust me with writing such code about as much as I’d trust my dog to build me a table :dog:

**Comment by sschuberth** [comment]
> I generated the `document.spdx.yml` yesterday for `mime-types` and in the result each packages is always a dependeny_of the root package (and not of another package):

As an update, that bit as been fixed with https://github.com/oss-review-toolkit/ort/pull/5126.

**Comment by sschuberth** [comment]
By now I really believe that the only bit missing from the original request is what I mentioned earlier:

> So this request is not so much about "not loosing hierarchy", but simply to "externalize" the related packages to separate files.

Would you agree @silverhook (and @maxhbr)? If so, is this externalization really still wanted, or was the main point to maintain the hierarchy (mostly independent of the representation), and this issue could be closed?

**Comment by maxhbr** [comment]
The issue also mentions the export of file level information, and that is not yet solved

**Comment by sschuberth** [comment]
Ok, I'm going to split this issue then; there's too much technically unrelated stuff being intertwined here.

**Comment by sschuberth** [comment]
Closing this in favor of the split-out issues, see the links above.
