### ISSUE TITLE
Yarn fails to download due to issuer certificate 

### ISSUE THREAD

**Issue by DaveJarvis** [oss-review-toolkit/ort#5748]
**Replicate**

The following steps may fail:

``` 
$ git clone https://github.com/oss-review-toolkit/ort
$ cd ort
$ ./gradlew clean installDist
```

**Expected**
Build succeeds.

**Actual**
Build fails with:

```
> Configure project :
Building ORT version 2d7b039a75-dirty.

> Task :reporter-web-app:yarnInstall
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@ant-design/colors/-/colors-6.0.0.tgz: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/home/username/repos/sandbox/ort/reporter-web-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> Task :reporter-web-app:yarnInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reporter-web-app:yarnInstall'.
> Process 'command '/home/username/.gradle/nodejs/node-v16.13.0-linux-x64/bin/node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
86 actionable tasks: 62 executed, 14 from cache, 10 up-to-date
```

**Work around**
Update the `.yarnrc` file:

``` bash
$ echo "strict-ssl false" >> $HOME/.yarnrc
```

**Comment by sschuberth** [comment]
> unable to get local issuer certificate

That sounds to me as if it's a problem with your local setup. Are you maybe behind a corporate proxy that tampers with SSL certificates? Also see [this answer](https://stackoverflow.com/a/30341389/1127485) on StackOverflow.

**Comment by DaveJarvis** [comment]
> Are you maybe behind a corporate proxy that tampers with SSL certificates?

That seems to be the case. We have to install custom certs for Java. Also, Gradle wouldn't download its .zip archive, which was strange because usually installing the cert is sufficient for Gradle to work.

**Comment by sschuberth** [comment]
Ok, then there's probably nothing on the ORT side we can do to address this. You might, however, want to have a look at the related [scripts](https://github.com/oss-review-toolkit/ort/tree/main/scripts) we provide and how we're using them in the [Dockerfile](https://github.com/oss-review-toolkit/ort/blob/main/Dockerfile) to get an idea how to tackle the issue on your side.

**Comment by DaveJarvis** [comment]
Consider adding an example to the documentation. I've been trying to figure this out for a while and it isn't immediately obvious how to build with a custom certificate. For example, I've tried:

    git clone https://github.com/oss-review-toolkit/ort
    ~/dev/ort$ DOCKER_BUILDKIT=1 docker build --build-arg CRT_FILES=proxy.crt .

This doesn't work out-of-the-box. We've changed

The ordering of the commands may be incorrect in the Dockerfile. For example, we couldn't get gradle to build until after we moved the copying of certificates above, such as:

``` docker
WORKDIR /usr/local/src/ort

ARG CRT_FILES
COPY "$CRT_FILES" /tmp/certificates/

# Allow operating system to download remote files
RUN mkdir -p /usr/local/share/ca-certificates/custom/
RUN cp /tmp/certificates/* /usr/local/share/ca-certificates/custom/
RUN update-ca-certificates

# Gradle build.
ARG ORT_VERSION
RUN --mount=type=cache,target=/tmp/.gradle/ \
    export GRADLE_USER_HOME=/tmp/.gradle/ && \
    scripts/import_certificates.sh /tmp/certificates/ && \
    scripts/import_proxy_certs.sh && \
    scripts/set_gradle_proxy.sh && \
    ./gradlew --no-daemon --stacktrace -Pversion=$ORT_VERSION :cli:distTar :helper-cli:startScripts
```

**Comment by sschuberth** [comment]
> Consider adding an example to the documentation.

Pull requests are welcome! Please note your [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md).

> This doesn't work out-of-the-box.

My understanding is that e.g. the people at Bosch are using the current mechanism to successfully inject certificates. Can you confirm @MarcelBochtler et al?

**Comment by sschuberth** [comment]
> Pull requests are welcome!

Nevermind, I'll come up with something as I just found more stuff I'd like to get addressed in this context.

**Comment by DaveJarvis** [comment]
> Pull requests are welcome!

After over an hour trying to make it work without success, a PR probably won't be forthcoming anytime soon.

>  the people at Bosch are using the current mechanism to successfully inject certificates

What commands are being issued to inject the cert?

**Comment by DaveJarvis** [comment]
Ran the following command with the attached Dockerfile:

``` bash
~/dev/ort$ DOCKER_BUILDKIT=1 docker build --build-arg CRT_FILES=proxy.crt .
```

Still failed. Tried numerous ways and settings to disable/work around the SSL issue. See attached log file.

[build.log](https://github.com/oss-review-toolkit/ort/files/9529935/build.log)

Try this:

``` bash
$ wget -qO- https://scala.jfrog.io/ui/native/debian/dists/all/InRelease | head
```

The response `<body>` shows that JavaScript is required:

``` xml
<div class="pounding-heart-container show-splash"><img class="logo pulse" src=/ui/img/jfrog.8f770bff.svg></div><noscript><strong>We're sorry but jfrog webapp doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script src=/ui/js/chunk-vendors.f3929bbf.js></script><script src=/ui/js/app.0f5d9740.js></script><script src=/ui/js/preloader.31ea7863.js></script>
```

This, of course, will break any command-line tooling. Not sure if it's related.

Revised Dockerfile:

[Dockerfile.txt](https://github.com/oss-review-toolkit/ort/files/9529898/Dockerfile.txt)

**Comment by DaveJarvis** [comment]
The following makes it most of the way through:

[Dockerfile.txt](https://github.com/oss-review-toolkit/ort/files/9537385/Dockerfile.txt)

Using the following incantation:

    DOCKER_BUILDKIT=1 docker -D build --network="host" --build-arg CRT_FILES=proxy.crt .

Results in:

```
#9 100.8 Hit:1 https://deb.nodesource.com/node_16.x jammy InRelease
#9 100.8 Get:2 https://scala.jfrog.io/ui/native/debian all InRelease
#9 100.8 Err:2 https://scala.jfrog.io/ui/native/debian all InRelease
#9 100.8   Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
#9 100.9 Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
#9 100.9 Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
#9 101.0 Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
#9 101.1 Get:6 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease [23.8 kB]
#9 101.2 Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
#9 103.1 Get:8 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy/main amd64 Packages [2,970 B]
#9 103.2 Reading package lists...
#9 104.6 E: Failed to fetch https://scala.jfrog.io/ui/native/debian/dists/all/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
#9 104.6 E: The repository 'https://scala.jfrog.io/ui/native/debian all InRelease' is not signed.
```

**Comment by DaveJarvis** [comment]
The latest problem appears to be that the Haskell shell scripts being pulled down themselves are using curl. However, curl isn't picking up the installed certificates. I tried loosening up the curl command by providing an alias:

    RUN alias curl='curl --cacert "/etc/ssl/certs/cacert.pem" --insecure '

The command still failed.
